lab_fimo_admin:
    resource: "@LabFimoAdminBundle/Resources/config/routing.yml"
    prefix:   /manage

lab_fimo_student:
    resource: "@LabFimoStudentBundle/Resources/config/routing.yml"
    prefix:   /

lab_fimo_security:
    resource: "@LabFimoSecurityBundle/Resources/config/routing.yml"
    prefix:   /

lab_fimo_dal:
    resource: "@LabFimoDALBundle/Resources/config/routing.yml"
    prefix: /
