# app/config/security.yml
security:
    encoders:
        LabFimo\SecurityBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        user_db:
            entity: { class: LabFimo\SecurityBundle\Entity\Usuario, property: usuario }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                csrf_provider: form.csrf_provider
                check_path:  login_check
                
    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
                    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Descomenta la siguiente línea para proteger también
        # la propia URL /admin
        # - { path: ^/admin$, roles: ROLE_ADMIN }
