<?php

namespace LabFimo\DALBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrigadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrigadaRepository extends EntityRepository {

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set claveBrigada
     *
     * @param integer $claveBrigada
     * @return Brigada
     */
    public function setClaveBrigada($claveBrigada) {
        $this->claveBrigada = $claveBrigada;

        return $this;
    }

    /**
     * Get claveBrigada
     *
     * @return integer 
     */
    public function getClaveBrigada() {
        return $this->claveBrigada;
    }

    /**
     * Set horaInicio
     *
     * @param \DateTime $horaInicio
     * @return Brigada
     */
    public function setHoraInicio($horaInicio) {
        $this->horaInicio = $horaInicio;

        return $this;
    }

    /**
     * Get horaInicio
     *
     * @return \DateTime 
     */
    public function getHoraInicio() {
        return $this->horaInicio;
    }

    /**
     * Set horaFin
     *
     * @param \DateTime $horaFin
     * @return Brigada
     */
    public function setHoraFin($horaFin) {
        $this->horaFin = $horaFin;

        return $this;
    }

    /**
     * Get horaFin
     *
     * @return \DateTime 
     */
    public function getHoraFin() {
        return $this->horaFin;
    }

    /**
     * Set esDisponible
     *
     * @param boolean $esDisponible
     * @return Brigada
     */
    public function setEsDisponible($esDisponible) {
        $this->esDisponible = $esDisponible;

        return $this;
    }

    /**
     * Get esDisponible
     *
     * @return boolean 
     */
    public function getEsDisponible() {
        return $this->esDisponible;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Brigada
     */
    public function setDescripcion($descripcion) {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string 
     */
    public function getDescripcion() {
        return $this->descripcion;
    }

    /**
     * Set comentarios
     *
     * @param string $comentarios
     * @return Brigada
     */
    public function setComentarios($comentarios) {
        $this->comentarios = $comentarios;

        return $this;
    }

    /**
     * Get comentarios
     *
     * @return string 
     */
    public function getComentarios() {
        return $this->comentarios;
    }

    public function getClaveDeClase() {
        return $this->claveBrigada;
    }

    public function setClaveDeClase($claveClase) {
        $this->claveBrigada = $claveClase;
        return $this;
    }

    /**
     * Get Plan
     * @return Brigada
     */
    public function getPlan() {
        return $this->plan;
    }

    /**
     * Set Plan
     *
     * @param string Plan
     * @return Brigada
     */
    public function setPlan($plan) {
        $this->plan = $plan;

        return $this;
    }

    /**
     * Get Clase
     * @return Brigada
     */
    public function getClase() {
        return $this->clase;
    }

    /**
     * Set Clase
     *
     * @param integer Clave
     * @return Brigada
     */
    public function setClase($clase) {
        $this->clase = $clase;

        return $this;
    }

    public function getEnrroles() {
        return $this->enrroles;
    }

    public function setEnrroles($enrrol) {
        $this->enrroles = $enrrol;

        return $this;
    }

    public function getInstructor() {
        return $this->instructor;
    }

    public function setInstrucor($instructor) {
        $this->instructor = $instructor;

        return $this;
    }

    public function getPractica() {
        return $this->practica;
    }

    public function setPractica($practica) {
        $this->practica = $practica;

        return $this;
    }

    /**
     * Add enrroles
     *
     * @param \LabFimo\DALBundle\Entity\Enrrol $enrroles
     * @return Brigada
     */
    public function addEnrrole(\LabFimo\DALBundle\Entity\Enrrol $enrroles) {
        $this->enrroles[] = $enrroles;

        return $this;
    }

    /**
     * Remove enrroles
     *
     * @param \LabFimo\DALBundle\Entity\Enrrol $enrroles
     */
    public function removeEnrrole(\LabFimo\DALBundle\Entity\Enrrol $enrroles) {
        $this->enrroles->removeElement($enrroles);
    }

    /**
     * Set instructor
     *
     * @param \LabFimo\DALBundle\Entity\Instructor $instructor
     * @return Brigada
     */
    public function setInstructor(\LabFimo\DALBundle\Entity\Instructor $instructor = null) {
        $this->instructor = $instructor;

        return $this;
    }

}