<?php

namespace LabFimo\DALBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnrrolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnrrolRepository extends EntityRepository {

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set mesaAsignada
     *
     * @param integer $mesaAsignada
     * @return Enrrol
     */
    public function setMesaAsignada($mesaAsignada) {
        $this->mesaAsignada = $mesaAsignada;

        return $this;
    }

    /**
     * Get mesaAsignada
     *
     * @return integer 
     */
    public function getMesaAsignada() {
        return $this->mesaAsignada;
    }

    /**
     * Set asistencia
     *
     * @param boolean $asistencia
     * @return Enrrol
     */
    public function setAsistencia($asistencia) {
        $this->asistencia = $asistencia;

        return $this;
    }

    /**
     * Get asistencia
     *
     * @return boolean 
     */
    public function getAsistencia() {
        return $this->asistencia;
    }

    public function getEstudiante() {
        return $this->estudiante;
    }

    public function setEstudiante($estudiante) {
        $this->estudiante = $estudiante;
    }

    public function getBrigada() {
        return $this->brigada;
    }

    public function setBrigada($brigada) {
        $this->brigada = $brigada;
        return $this;
    }

}
